### ISSUE TITLE
feat: Implement Raft as a storage backend

### ISSUE THREAD

**Issue by cabrinha** [kubevault/project#96]
Raft was introduced as a storage backend in vault version 1.4: https://www.vaultproject.io/docs/configuration/storage/raft.html

Let's add this as a valid backend to the operator, or let's allow the CRD to omit the `spec.backend` field and just go with the user provided `vault.hcl` configuration

It would also be good to implement StatefulSet instead of Deployment.

**Comment by tamalsaha** [comment]
@cabrinha , thanks for the enhancement request. We would love to have you contribute. Are you still interested?

**Comment by ron1** [comment]
Since Raft provides an easily-configured, highly-available storage backend for Vault, consider elevating the priority of this feature request.

**Comment by cabrinha** [comment]
> @cabrinha , thanks for the enhancement request. We would love to have you contribute. Are you still interested?

Sorry, no. Not at the moment. I think the Raft storage backend would be a little complicated for me to implement at this time.

**Comment by yoan-adfinis** [comment]
I've given it a try and there are the main issues found along the way.

- `retry_join` is kind of needed for the clusters to establish a Raft cluster.
- PVC support (I've copy'n'pasted the code from the file system and it's not ideal)

Both those issues put to light that it should probably be using a `StatefulSet` rather than a `ReplicaSet` for this specific storage. Which requires a fair amount of refactorting.
